version: '3'

services: 
    mysql:
        image: mysql:5.7
        ports: 
            - '3366:3306'
        
        environment: 
            MYSQL_DATABASE: teste
            #MYSQL_USER: 'root'
            MYSQL_PASSWORD: '1Malvezzi1'
            MYSQL_ROOT_PASSWORD: '1Malvezzi1'
        
        networks: 
            - main
        volumes:
            - .:/app

    back:
        build: ./fullstack/
        networks: 
            - main
        command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .dbdata:/bar/lib/mysql

        ports:
            - "8000:8000"

        depends_on: 
            - mysql

    front:
        build: ./frontend/frontendapi/
        networks: 
            - main
        command: npm start
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/frontendapi:/app
            - /app/node_modules

networks: 
    main:
          
        

    
            
            
